export const SET_OFFICIAL = "[SET_OFFICIAL]"
export const SET_RESERVATIONS = "[SET_RESERVATION]"
export const SET_RECIPS = "[SET_RECIPS]"
export const SET_HQ = "[SET_HQ]"
export const SET_QR = "[SET_QR]"
export const SET_QR_PHONE = "[SET_QR_PHONE]"